name: Release to GHCR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  build:
    name: Build rock
    uses: canonical/data-platform-workflows/.github/workflows/build_rock.yaml@v41.1.0

  release:
    name: Release rock
    needs:
      - build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |          
          sudo snap install yq
          sudo snap install rockcraft --classic

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v7

      - name: Publish Image to Channel
        run: |
          ls
          # Unpack artifact
          # mv charmed-spark/${{ steps.artifact.outputs.base_artifact_name }} .
          ROCK_FILE=$(ls *.rock)
          echo "Rock file: ${ROCK_FILE}"
          IMAGE_NAME="ghcr.io/welpaolo/charmed-spark-integration-hub"
          TAG="3"
          sudo rockcraft.skopeo --insecure-policy copy \
            oci-archive:${ROCK_FILE} \
            docker-daemon:${IMAGE_NAME}:${TAG}
          echo "1"
          COMMIT_ID=$(git log -1 --format=%H)
          DESCRIPTION=$(yq .description rockcraft.yaml | xargs)
          
          # Add relevant labels
          echo "FROM ${IMAGE_NAME}:${TAG}" | docker build --label org.opencontainers.image.description="${DESCRIPTION}" --label org.opencontainers.image.revision="${COMMIT_ID}" --label org.opencontainers.image.source="${{ github.repositoryUrl }}" -t "${IMAGE_NAME}:${TAG}" -
          echo "2"
          echo "Publishing ${IMAGE_NAME}:${TAG}"          
          docker push ${IMAGE_NAME}:${TAG}

          echo "3"
